services:
  database:
    restart: unless-stopped
    build: ./geo-app-database
    hostname: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geo-app

  server:
    restart: on-failure
    build: ./geo-app-server
    hostname: geo-app-server
    depends_on:
      - database
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: geo-app-nginx
    ports:
      - "3001:3001"
    depends_on:
      - server