# Используем официальный образ для PostgreSQL
FROM postgres:13

# Устанавливаем переменные окружения для настройки базы данных
ENV POSTGRES_DB=geo_app
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password

EXPOSE 5432